project_name: kubegraph

builds:
  - id: kubegraph
    main: ./src/main.go
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    binary: kubegraph
    ldflags:
      - -s -w
    hooks:
      post: 
        - |
          echo "Running unit test..."
          kustomize build ./ArgoCD/SampleApp/tests/. | ./dist/kubegraph_linux_amd64_v1/kubegraph --rules ./ArgoCD/SampleApp/rules.yaml
          echo "Done running unit test! Passed!"

checksum:
  name_template: 'checksums.txt'

release:
  github:
    owner: td4b
    name: KubeGraph
