project_name: kubegraph

builds:
  - id: kubegraph
    main: ./main.go
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    binary: kubegraph
    ldflags:
      - -s -w

archives:
  - format: tar.gz
    files:
      - LICENSE
      - README.md

checksum:
  name_template: 'checksums.txt'

release:
  github:
    owner: YOUR_GITHUB_USER
    name: YOUR_REPO
