project_name: kubegraph

builds:
  - id: kubegraph
    main: main.go
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    binary: kubegraph
    ldflags:
      - -s -w

checksum:
  name_template: 'checksums.txt'

release:
  github:
    owner: td4b
    name: KubeGraph
