rules:
  - match:
      kind: Ingress
      metadata:
        annotations:
          kubegraph: managed
    inject:
      metadata:
        annotations:
          kubegraphpatch: "applied"
    injectFile: "inject-file.yaml"
    newResources:
      - ./render/route.yaml
      - ./render/middleware.yaml
