apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

helmCharts:
  - name: argo-cd
    repo: https://argoproj.github.io/argo-helm
    version: 8.1.2
    releaseName: argocd
    namespace: argocd
    valuesFile: argocd-values.yaml

resources:
  - app.yaml
  - plugin.yaml

patches:
  - path: ./patches/patch-repo-server.yaml

