apiVersion: v1
kind: ConfigMap
metadata:
  name: my-plugin-config
  namespace: argocd
data:
  plugin.yaml: |
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: kubegraph
      namespace: argocd
    spec:
      version: v1.0.1
      generate:
        command: [sh, -c]
        args:
          - |
            # It's recommended here to distribute your rules and standard templates
            # in the sidecar container 
            kustomize build . | kubegraph --rules ./template/rules.yaml
