apiVersion: v1
kind: ConfigMap
metadata:
  name: my-plugin-config
  namespace: argocd
data:
  plugin.yaml: |
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: kubegraph
      namespace: argocd
    spec:
      version: v1.0.1
      generate:
        command: [sh, -c]
        args:
          - |
            echo "🔍 Running kustomize build | kubegraph..."
            kustomize build ./ArgoCD/SampleApp | kubegraph
