apiVersion: argoproj.io/v1alpha1
kind: ConfigManagementPlugin
metadata:
  name: gotempalter
spec:
  version: v1.0
  init:
    command: [sh, -c]
    args:
      - |
        echo "🔍 Downloading gotempalter..."
        curl -sSL -o ./gotempalter https://github.com/YOUR_GITHUB_USER/YOUR_REPO/releases/download/v1.0.0/gotempalter-linux-amd64

        echo "🔍 Verifying SHA256..."
        echo "YOUR_EXPECTED_SHA256  gotempalter" | sha256sum -c -

        echo "🔍 Making it executable..."
        chmod +x ./gotempalter
  generate:
    command: [sh, -c]
    args:
      - |
        echo "🔍 Running kustomize build | gotempalter..."
        kustomize build . | ./gotempalter
