apiVersion: argoproj.io/v1alpha1
kind: ConfigManagementPlugin
metadata:
  name: gotempalter
spec:
  version: v1.0
  init:
    command: [sh, -c]
    args:
      - |
        echo "🔍 Downloading gotempalter..."
        curl -sSL -o ./kubegraph.tar.gz https://github.com/td4b/KubeGraph/releases/download/v1.0.0/kubegraph_1.0.0_linux_amd64.tar.gz

        echo "🔍 Verifying SHA256..."
        echo "58f8ddac2b41e1c40b486a22223f49b0f74a09e9c1f16ce3a97e943e3aa55fc5  kubegraph.tar.gz" | sha256sum -c -

        echo "UnPacking"
        tar -xvf kubegraph.tar.gz
        echo "Done, KubeGraph is Ready!"

  generate:
    command: [sh, -c]
    args:
      - |
        echo "🔍 Running kustomize build | gotempalter..."
        kustomize build . | ./kubegraph
