apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: "{{ resource "kind.Ingress.metadata.annotations.kubegraph.managed & metadata.name" }}-route"
  namespace: foo
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`bar`) && PathPrefix(`/path`)
      kind: Rule
      services:
        - name: bar-svc
          port: 80
          