apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ resource "kind.Ingress.metadata.annotations.kubegraph.managed & metadata.name" }}-route
  namespace: {{ resource "kind.Ingress.metadata.annotations.kubegraph.managed & metadata.namespace" }}
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`{{ resource "kind.Ingress.metadata.annotations.kubegraph.managed & spec.rules.0.host" }}`) && PathPrefix(`/path`)
      kind: Rule
      services:
        - name: some-service
          port: 80
  tls:
    secretName:  {{ resource "kind.Ingress.metadata.annotations.kubegraph.managed & spec.tls.secretName" }}
    