name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Build & Publish kubegraph Release
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # --- Build & push Docker image ---
      
      - name: Log in to Docker registry
        uses: docker/login-action@v3
        with:
          username: tdub17
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build Docker image
        run: |
         docker build -t tdub17/kubegraph:${{ github.ref_name }} .

      - name: Push Docker image
        run: |
          docker push tdub17/kubegraph:${{ github.ref_name }}
